
package client;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "bdd", targetNamespace = "")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Bdd {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "rep", partName = "rep")
    public String getAll();

    /**
     * 
     * @param question
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "rep", partName = "rep")
    public String getOne(
        @WebParam(name = "question", partName = "question")
        BigInteger question);

    /**
     * 
     * @param ip
     * @param deviceData
     * @return
     *     returns java.math.BigInteger
     */
    @WebMethod
    @WebResult(name = "rep", partName = "rep")
    public BigInteger getId(
        @WebParam(name = "ip", partName = "ip")
        String ip,
        @WebParam(name = "device_data", partName = "device_data")
        String deviceData);

    /**
     * 
     * @param reponse
     * @param question
     * @param auth
     * @param id
     * @return
     *     returns java.math.BigInteger
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public BigInteger submitAns(
        @WebParam(name = "id", partName = "id")
        BigInteger id,
        @WebParam(name = "question", partName = "question")
        BigInteger question,
        @WebParam(name = "reponse", partName = "reponse")
        String reponse,
        @WebParam(name = "auth", partName = "auth")
        String auth);

}
