
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "bdd", targetNamespace = "bdd", wsdlLocation = "http://localhost:8888/SoaPOC/bddServ.wsdl")
public class Bdd_Service
    extends Service
{

    private final static URL BDD_WSDL_LOCATION;
    private final static WebServiceException BDD_EXCEPTION;
    private final static QName BDD_QNAME = new QName("", "bdd");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/SoaPOC/bddServ.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BDD_WSDL_LOCATION = url;
        BDD_EXCEPTION = e;
    }

    public Bdd_Service() {
        super(__getWsdlLocation(), BDD_QNAME);
    }

    public Bdd_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BDD_QNAME, features);
    }

    public Bdd_Service(URL wsdlLocation) {
        super(wsdlLocation, BDD_QNAME);
    }

    public Bdd_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BDD_QNAME, features);
    }

    public Bdd_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Bdd_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Bdd
     */
    @WebEndpoint(name = "bdd")
    public Bdd getBdd() {
        return super.getPort(new QName("", "bdd"), Bdd.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Bdd
     */
    @WebEndpoint(name = "bdd")
    public Bdd getBdd(WebServiceFeature... features) {
        return super.getPort(new QName("", "bdd"), Bdd.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BDD_EXCEPTION!= null) {
            throw BDD_EXCEPTION;
        }
        return BDD_WSDL_LOCATION;
    }

}
